name: icc_maps
description: "A new Flutter project."
publish_to: 'isy99801'
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.7
  provider: ^6.1.2
  dart_converters: ^0.0.3
  http: ^1.2.2
  google_maps_flutter: ^2.5.3
  flutter_map_geojson: ^1.0.5
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  image: ^4.1.7
  path_provider: ^2.1.3
  sqflite: ^2.0.0+4
  path: ^1.8.0
  flutter_svg: ^2.0.10+1
  dio: ^5.5.0+1
  geolocator: ^11.1.0
  material_symbols_icons: ^4.2784.0 
  turf: ^0.0.10
  firebase_core: ^2.27.0
  multi_select_flutter: ^4.1.3
  permission_handler: ^10.2.0
  file_picker: ^8.0.0+1
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.0.0+4 
flutter:
  uses-material-design: true
  assets:
    - assets/images/icclaro.png
    - assets/icons/icon.png
    - assets/images/background.jpg
    - assets/images/clarologo.png
    - assets/images/icc_claro_appbar.png
    - assets/geojson/puerto_rico.geojson
