import 'package:flutter/material.dart';

final List<DropdownMenuItem<String>> townsList = [
  const DropdownMenuItem(value: 'Adjuntas', child: Text('Adjuntas')),
  const DropdownMenuItem(value: 'Aguada', child: Text('Aguada')),
  const DropdownMenuItem(value: 'Aguadilla', child: Text('Aguadilla')),
  const DropdownMenuItem(value: 'Aguas Buenas', child: Text('Aguas Buenas')),
  const DropdownMenuItem(value: 'Aibonito', child: Text('Aibonito')),
  const DropdownMenuItem(value: 'Arecibo', child: Text('Arecibo')),
  const DropdownMenuItem(value: 'Arroyo', child: Text('Arroyo')),
  const DropdownMenuItem(value: 'Añasco', child: Text('Añasco')),
  const DropdownMenuItem(value: 'Barceloneta', child: Text('Barceloneta')),
  const DropdownMenuItem(value: 'Barranquitas', child: Text('Barranquitas')),
  const DropdownMenuItem(value: 'Bayamón', child: Text('Bayamón')),
  const DropdownMenuItem(value: 'Cabo Rojo', child: Text('Cabo Rojo')),
  const DropdownMenuItem(value: 'Caguas', child: Text('Caguas')),
  const DropdownMenuItem(value: 'Camuy', child: Text('Camuy')),
  const DropdownMenuItem(value: 'Canóvanas', child: Text('Canóvanas')),
  const DropdownMenuItem(value: 'Carolina', child: Text('Carolina')),
  const DropdownMenuItem(value: 'Cataño', child: Text('Cataño')),
  const DropdownMenuItem(value: 'Cayey', child: Text('Cayey')),
  const DropdownMenuItem(value: 'Ceiba', child: Text('Ceiba')),
  const DropdownMenuItem(value: 'Ciales', child: Text('Ciales')),
  const DropdownMenuItem(value: 'Cidra', child: Text('Cidra')),
  const DropdownMenuItem(value: 'Coamo', child: Text('Coamo')),
  const DropdownMenuItem(value: 'Comerío', child: Text('Comerío')),
  const DropdownMenuItem(value: 'Corozal', child: Text('Corozal')),
  const DropdownMenuItem(value: 'Culebra', child: Text('Culebra')),
  const DropdownMenuItem(value: 'Dorado', child: Text('Dorado')),
  const DropdownMenuItem(value: 'Fajardo', child: Text('Fajardo')),
  const DropdownMenuItem(value: 'Florida', child: Text('Florida')),
  const DropdownMenuItem(value: 'Guayama', child: Text('Guayama')),
  const DropdownMenuItem(value: 'Guayanilla', child: Text('Guayanilla')),
  const DropdownMenuItem(value: 'Guaynabo', child: Text('Guaynabo')),
  const DropdownMenuItem(value: 'Gurabo', child: Text('Gurabo')),
  const DropdownMenuItem(value: 'Guánica', child: Text('Guánica')),
  const DropdownMenuItem(value: 'Hatillo', child: Text('Hatillo')),
  const DropdownMenuItem(value: 'Hormigueros', child: Text('Hormigueros')),
  const DropdownMenuItem(value: 'Humacao', child: Text('Humacao')),
  const DropdownMenuItem(value: 'Isabela', child: Text('Isabela')),
  const DropdownMenuItem(value: 'Jayuya', child: Text('Jayuya')),
  const DropdownMenuItem(value: 'Juana Díaz', child: Text('Juana Díaz')),
  const DropdownMenuItem(value: 'Juncos', child: Text('Juncos')),
  const DropdownMenuItem(value: 'Lajas', child: Text('Lajas')),
  const DropdownMenuItem(value: 'Lares', child: Text('Lares')),
  const DropdownMenuItem(value: 'Las Marías', child: Text('Las Marías')),
  const DropdownMenuItem(value: 'Las Piedras', child: Text('Las Piedras')),
  const DropdownMenuItem(value: 'Loíza', child: Text('Loíza')),
  const DropdownMenuItem(value: 'Luquillo', child: Text('Luquillo')),
  const DropdownMenuItem(value: 'Manatí', child: Text('Manatí')),
  const DropdownMenuItem(value: 'Maricao', child: Text('Maricao')),
  const DropdownMenuItem(value: 'Maunabo', child: Text('Maunabo')),
  const DropdownMenuItem(value: 'Mayagüez', child: Text('Mayagüez')),
  const DropdownMenuItem(value: 'Moca', child: Text('Moca')),
  const DropdownMenuItem(value: 'Morovis', child: Text('Morovis')),
  const DropdownMenuItem(value: 'Naguabo', child: Text('Naguabo')),
  const DropdownMenuItem(value: 'Naranjito', child: Text('Naranjito')),
  const DropdownMenuItem(value: 'Orocovis', child: Text('Orocovis')),
  const DropdownMenuItem(value: 'Patillas', child: Text('Patillas')),
  const DropdownMenuItem(value: 'Peñuelas', child: Text('Peñuelas')),
  const DropdownMenuItem(value: 'Ponce', child: Text('Ponce')),
  const DropdownMenuItem(value: 'Quebradillas', child: Text('Quebradillas')),
  const DropdownMenuItem(value: 'Rincón', child: Text('Rincón')),
  const DropdownMenuItem(value: 'Río Grande', child: Text('Río Grande')),
  const DropdownMenuItem(value: 'Sabana Grande', child: Text('Sabana Grande')),
  const DropdownMenuItem(value: 'Salinas', child: Text('Salinas')),
  const DropdownMenuItem(value: 'San Germán', child: Text('San Germán')),
  const DropdownMenuItem(value: 'San Juan', child: Text('San Juan')),
  const DropdownMenuItem(value: 'San Lorenzo', child: Text('San Lorenzo')),
  const DropdownMenuItem(value: 'San Sebastián', child: Text('San Sebastián')),
  const DropdownMenuItem(value: 'Santa Isabel', child: Text('Santa Isabel')),
  const DropdownMenuItem(value: 'Toa Alta', child: Text('Toa Alta')),
  const DropdownMenuItem(value: 'Toa Baja', child: Text('Toa Baja')),
  const DropdownMenuItem(value: 'Trujillo Alto', child: Text('Trujillo Alto')),
  const DropdownMenuItem(value: 'Utuado', child: Text('Utuado')),
  const DropdownMenuItem(value: 'Vega Alta', child: Text('Vega Alta')),
  const DropdownMenuItem(value: 'Vega Baja', child: Text('Vega Baja')),
  const DropdownMenuItem(value: 'Vieques', child: Text('Vieques')),
  const DropdownMenuItem(value: 'Villalba', child: Text('Villalba')),
  const DropdownMenuItem(value: 'Yabucoa', child: Text('Yabucoa')),
  const DropdownMenuItem(value: 'Yauco', child: Text('Yauco')),
];
