// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuOFeS9rXDUJc_VHP6WqvilWIFMzM0xfA',
    appId: '1:764673773227:web:1fda6dd5aa0e58d8d7b1ee',
    messagingSenderId: '764673773227',
    projectId: 'tasklist-dartfrog-64a2c',
    authDomain: 'tasklist-dartfrog-64a2c.firebaseapp.com',
    storageBucket: 'tasklist-dartfrog-64a2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUESHFY7EzO2SBWCwVRrRI2qJPMxkeikQ',
    appId: '1:764673773227:android:1a42c65295ea6808d7b1ee',
    messagingSenderId: '764673773227',
    projectId: 'tasklist-dartfrog-64a2c',
    storageBucket: 'tasklist-dartfrog-64a2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOJs8Uxt1sN2gC-0cSjMODoy9wQCeCc1Y',
    appId: '1:764673773227:ios:fe1c6595f346cf31d7b1ee',
    messagingSenderId: '764673773227',
    projectId: 'tasklist-dartfrog-64a2c',
    storageBucket: 'tasklist-dartfrog-64a2c.appspot.com',
    iosBundleId: 'com.example.flutterParamWidget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOJs8Uxt1sN2gC-0cSjMODoy9wQCeCc1Y',
    appId: '1:764673773227:ios:fe1c6595f346cf31d7b1ee',
    messagingSenderId: '764673773227',
    projectId: 'tasklist-dartfrog-64a2c',
    storageBucket: 'tasklist-dartfrog-64a2c.appspot.com',
    iosBundleId: 'com.example.flutterParamWidget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuOFeS9rXDUJc_VHP6WqvilWIFMzM0xfA',
    appId: '1:764673773227:web:1fda6dd5aa0e58d8d7b1ee',
    messagingSenderId: '764673773227',
    projectId: 'tasklist-dartfrog-64a2c',
    authDomain: 'tasklist-dartfrog-64a2c.firebaseapp.com',
    storageBucket: 'tasklist-dartfrog-64a2c.appspot.com',
  );
}
