// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTe8GtI9RO_MxzoQBtgd_mn3XL2qHsQZU',
    appId: '1:281322845329:web:2fc9e02d427db0314abb30',
    messagingSenderId: '281322845329',
    projectId: 'iccclaroapp',
    authDomain: 'iccclaroapp.firebaseapp.com',
    storageBucket: 'iccclaroapp.firebasestorage.app',
    measurementId: 'G-2MSY49GCFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN6Z73FUjnnBTJdext1l5KJVh1ffgwzJQ',
    appId: '1:281322845329:android:c93f187a56ae43394abb30',
    messagingSenderId: '281322845329',
    projectId: 'iccclaroapp',
    storageBucket: 'iccclaroapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALDFi6Ccx4tXc3_pkQX17G9daVHmLTD1A',
    appId: '1:281322845329:ios:343e7c0a45db26114abb30',
    messagingSenderId: '281322845329',
    projectId: 'iccclaroapp',
    storageBucket: 'iccclaroapp.firebasestorage.app',
    iosBundleId: 'claro.app.mobile.iccClaroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALDFi6Ccx4tXc3_pkQX17G9daVHmLTD1A',
    appId: '1:281322845329:ios:343e7c0a45db26114abb30',
    messagingSenderId: '281322845329',
    projectId: 'iccclaroapp',
    storageBucket: 'iccclaroapp.firebasestorage.app',
    iosBundleId: 'claro.app.mobile.iccClaroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTe8GtI9RO_MxzoQBtgd_mn3XL2qHsQZU',
    appId: '1:281322845329:web:0e415abfee4608484abb30',
    messagingSenderId: '281322845329',
    projectId: 'iccclaroapp',
    authDomain: 'iccclaroapp.firebaseapp.com',
    storageBucket: 'iccclaroapp.firebasestorage.app',
    measurementId: 'G-NMV35TL2EH',
  );
}
